trigger:
- main

pool:
    vmImage: 'ubuntu-latest'

variables:
  IMAGE_REGISTRY_CONNECTION: 'DockerHub'
  IMAGE_REGISTRY: 'adodemo'
  IMAGE_REPOSITORY: 'denisatdocker/adodemo'
  TAG: '$(Build.BuildId)'

stages:
- stage: BuildApp
  jobs: 
  - job: BuildPushImage
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'denisatdocker/adodemo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
